author: croxis, kikelkik
main: com.minecraftcorp.lift.bukkit.LiftPlugin
name: LiftReloaded
version: ${project.version}
description: Simple and realistic elevators
softdepend: [NoCheatPlus, NoteBlockAPI]
permissions:
  lift:
    description: Can ride in a lift
    default: true
  lift.change:
    description: Can change lift floors
    default: true
  lift.reload:
    description: Reloads the lift plugin
    default: op
commands:
   lift:
      description: Scans a lift.
      usage: /<command>
      permission: lift
      permission-message: You don't have lift permissions
api-version: 1.17