name: Publish Release

on:
  release:
    types: [published]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Extract Version
        id: extract_version
        run: |
          TAG_NAME="${{ github.event.release.tag_name }}"
          VERSION="${TAG_NAME#lift-reloaded-}"
          echo "version=$VERSION" >> $GITHUB_OUTPUT

      - name: Set up Java 21
        uses: actions/setup-java@v4
        with:
          java-version: 21
          distribution: temurin
          cache: maven

      - name: Build and package Maven project
        run: mvn -B clean package

      - name: Upload to release
        uses: cloudnode-pro/release-upload-asset@1.0.2
        with:
          gh-token: ${{ github.token }}
          files: target/lift-reloaded-${{ steps.extract_version.outputs.version }}.jar; type=application/java-archive

      - name: Publish to Modrinth
        uses: cloudnode-pro/modrinth-publish@2.0.0
        with:
          token: ${{ secrets.MODRINTH_TOKEN }}
          project: ${{ secrets.MODRINTH_PROJECT_ID }}
          name: ${{ github.event.release.name }}
          version: ${{ steps.extract_version.outputs.version }}
          changelog: ${{ github.event.release.body }}
          files: target/lift-reloaded-${{ steps.extract_version.outputs.version }}.jar
          loaders: '["bukkit", "paper", "spigot"]'
          game-versions: '["1.21.x"]'
